services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx-server
    restart: unless-stopped
    ports:
      - "1883:1883"      # MQTT
      - "8083:8083"      # WebSockets
      - "18083:18083"    # Dashboard (Interna/HTTP)
      - "8084:8084"      # WebSockets (SSL)
      - "8883:8883"      # MQTT (SSL)
      - "18084:18084"    # Dashboard (SSL nativa EMQX - opzionale se usi Caddy)
      - "443:8883"       # Bind 443 su 8883 per porta alternativa
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
      - /etc/letsencrypt:/opt/emqx/etc/certs/letsencrypt:ro
    environment:
      - EMQX_LISTENERS__SSL__DEFAULT__BIND=0.0.0.0:8883
      - EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__KEYFILE=/opt/emqx/etc/certs/letsencrypt/live/stage-mqtt.clara.help/privkey.pem
      - EMQX_LISTENERS__SSL__DEFAULT__SSL_OPTIONS__CERTFILE=/opt/emqx/etc/certs/letsencrypt/live/stage-mqtt.clara.help/fullchain.pem

  caddy:
    image: caddy:latest
    container_name: caddy-proxy
    restart: unless-stopped
    ports:
      - "8443:443"  # Mappa la 443 interna di Caddy sulla 8443 esterna
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /etc/letsencrypt:/data/certs:ro # Monta i certificati anche qui
    depends_on:
      - emqx

volumes:
  emqx-data:
  emqx-log:
